pull_request_rules:
  - name: "test for https://github.com/Mergifyio/mergify-engine/issues/523"
    conditions:
      - author=jatcwang
      - status-success="test"
      - "#files=1"
      - files=build.sbt
    actions:
      merge:
        method: merge
        #strict: smart+fasttrack
  - name: automatic merge for scala-steward pull requests affecting build.sbt
    conditions:
      - author=scala-steward
      - status-success="test"
      - "#files=1"
      - files=build.sbt
    actions:
      merge:
        method: merge
        #strict: smart+fasttrack
  - name: automatic merge for scala-steward pull requests affecting project plugins.sbt
    conditions:
      - author=scala-steward
      - status-success="test"
      - "#files=1"
      - files=project/plugins.sbt
    actions:
      merge:
        method: merge
        #strict: smart+fasttrack
  - name: semi-automatic merge for scala-steward pull requests
    conditions:
      - author=scala-steward
      - status-success="test"
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
        #strict: smart+fasttrack
  - name: automatic merge for scala-steward pull requests affecting project build.properties
    conditions:
      - author=scala-steward
      - status-success="test"
      - "#files=1"
      - files=project/build.properties
    actions:
      merge:
        method: merge
        #strict: smart+fasttrack
  - name: automatic merge for scala-steward pull requests affecting .scalafmt.conf
    conditions:
      - author=scala-steward
      - status-success="test"
      - "#files=1"
      - files=.scalafmt.conf
    actions:
      merge:
        method: merge
#        strict: smart+fasttrack
