addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.19")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.2")
addSbtPlugin("pl.project13.scala" % "sbt-jmh" % "0.4.2")
addSbtPlugin("com.geirsson" % "sbt-ci-release" % "1.5.7")
addSbtPlugin("com.47deg" % "sbt-microsites" % "1.3.4")
addSbtPlugin("com.codecommit" % "sbt-github-actions" % "0.10.1")
//addSbtPlugin("com.typesafe" % "sbt-mima-plugin" % "0.8.1")
